### PR TITLE
Feature/chat room endpoint schema

### PR DESCRIPTION
**Pull request by don-tay**
## Changes in this PR

-   [ ] Bug fix
-   [x] New feature
-   [ ] Breaking change of an existing feature
-   [ ] Refactor/Performance enhancements

## Overview

- Chat room endpoints, including chatroom creation, send message, update last seen, get all chatrooms for user, and get single chatroom with messages

### CODE REVIEW

**Comment by don-tay** [comment]
Schema plan

`chatroom`
`chatroom_id` - UUID


table that shows the chatrooms each user is in
`chatroomuser`
`user_id` - UUID reference `user`
`chatroom_ids` - UUID[] reference `chatroom`


For `chatroomuser`, it is currently implemented somewhat like a "pseudo" junction table, to avoid having too many rows in the table. Considering that 1 user can make unlimited chatrooms with unlimited users (and with multiple to 1 users as well). The number of chatrooms can greatly increase. Hence, we may need to restrategise how we should plan the schema and application logic for the chatroom.

cc @faqihisaninja

**Comment by don-tay** [comment]
1. POST Create chatroom
Request body
```
{
        chatroom_name: string
        chatroom_pic: string
        is_dm: boolean
        user_ids: string[]
}
```
Response (200 OK)
```
{
	chatroom_id: UUID
	chatroom_name: string
	chatroom_pic: string
	is_dm: boolean
	user_ids: string[]
	created_on: Date
	updated_on: Date
}
```

**Comment by don-tay** [comment]
2. GET all chatroom for user (by user id)
URI: /api/users/:user_id/chatrooms
Response (200 OK)
```
{
  chatroom_id: UUID
  chatroom_name: string
  chatroom_pic: string
  is_dm: boolean
  most_recent_msg: 
    {
      chatmessage_text: string
      created_on: Date
      user_id: UUID
    }
```

**Comment by don-tay** [comment]
3. GET chatroom by chatroom ID
URL: /api/chatroom/:chatroom_id
Response (200 OK)
```
{
  users: { user_id: UUID, nickname: string, profile_picture: string }[]
  messages: {
    chatmessage_id: number
    user_id: UUID
    chatmessage_text: string
    reply_to: number
    file_links: string[]
    created_on: Date
    updated_on: Date
  }[]
}
```

**Comment by don-tay** [comment]
4. POST Send message in chatroom
URL: /api/chatrooms/:chatroom_id/message
Request body:
```
{
  chatroom_id: UUID
  chatmessage_text: string
  reply_to: number
  file_links: string[]
}
```
Response (200 OK)
```
{
  chatmessageid: number
  user_id: UUID
  chatmessage_text: string
  reply_to: number
  file_links: string[]
  created_on: Date
  updated_on: Date
}
```

**Comment by don-tay** [comment]
5. PUT Update last seen of current user
URL: /api/chatrooms/:chatroom_id/update-last-seen
Request body:
```
// Empty body
```

Response (200 OK)
```
{
  success: true,
  last_seen: Date
}
```

**Review by Kalsyc — APPROVED** [review]
Looks good for now :)

**Pull request merged**
